### ISSUE TITLE
Sonarr/Radarr doesn't detect downloaded files until manual action

### ISSUE THREAD

**Issue by Michsior14** [ghostserverd/mediaserver-docker#14]
Because Sonarr/Radarr do not mark files as downloaded Bazarr won't download subtitles until manual trigger of `Update series and scan disc` is performed. Is there any solution for it?

I guess this is similar to the problem described in [here](https://forums.sonarr.tv/t/sonarr-filebot-transmission-and-completed-download-handling-problems-solution/13654).

@ghostserverd What do you think about performing an API call to `Sonarr`/`Raddar`/`Bazarr` once `filebot` finish processing of the file?

**Comment by Michsior14** [comment]
Soo, I tried that on forked `qBittorrent` [image](https://github.com/Michsior14/docker-qbittorrent-ghost/blob/master/qbit-postprocess.sh#L31) and it seems to work fine.

**Comment by ghostserverd** [comment]
That's a good idea. I'll make the change to the transmission postprocess script. Unfortunately it doesn't look like transmission will pass me the label properly (or maybe the PVRs aren't setting it properly when starting a download) so I'm going to check the download directory for `sonarr` or `radarr` which isn't ideal but should work OK since specifying a category in sonarr and radarr explicitly creates a subdirectory from the category to download in.

Also heads up I think you have a typo in your qbitorrent implementation. [This](https://github.com/Michsior14/docker-qbittorrent-ghost/blob/5ee2ad5cf684d100a82918492142c317225ed921/qbit-postprocess.sh#L40) should probably be `http://radarr:` instead of `http://raddar:`

**Comment by ghostserverd** [comment]
https://github.com/ghostserverd/docker-transmission-ghost/commit/4d1d777abcf6dfaba8cb5585a5aeee2851c04ac2
