### ISSUE TITLE
Sonarr and Radarr failed to authenticate with Transmission when "rpc-authentication-required": false

### ISSUE THREAD

**Issue by jakobwarrer** [ghostserverd/mediaserver-docker#18]
When I followed the readme, and came to adding transmission to sonarr it kept failing with "Authentication failure", I tried leaving the .env blank for it to default to ```admin/adminadmin``` still no, I even tried leaving Username and Password blank in sonarr, still no dice.

After some messing about, I saw in the config file for transmission that ```rpc-authentication-required``` was set to ```false```, on hunch I tried setting it to ```true```, and now it works in both sonarr and radarr, it would seem radarr and sonarr can't handle not having to authenticate

**Comment by ghostserverd** [comment]
The settings default to `"rpc-authentication-required": true`. Did you change it manually?

https://github.com/ghostserverd/docker-transmission-ghost/blob/976d679275af76117d7174fa585fc4f70a511dd7/settings.json#L43

**Comment by carefreecaribou** [comment]
I have a similar issue. I just redeployed the docker-compose. Transmission's settings.json also appeared to me as `"rpc-authentication-required": false`. I have not previously touched the settings.json file and changing this to true did not help me, but changing the host did.

If  change the host from `transmission` to my local device ip address, it authenticates perfectly fine.

I only think these two issues may be related because our rpc authentication both defaulted to false.

**Comment by carefreecaribou** [comment]
I actually fixed this by coping the majority of the settings.json from here. For some reason, it didn't have many of the default options. After, it successfully worked and allowed me to call transmission in sonarr and radarr.

**Comment by ghostserverd** [comment]
The issue is that there's a default `settings.json` being written before the startup script is run, so when the startup script runs, the `cp -n` to copy in our custom `settings.json` doesn't overwrite the existing file.

I made a change to check if `rpc-authentication-required` is set to `true`, and if it's not, we'll assume that the file isn't a good one and overwrite it with the default one in this repo.

IMO this is a safe change to make because `auth` should always be enabled (especially since this meant to be hosted on the public internet with the letsencrypt container) and this won't break custom configs as long as they have `auth` enabled.

https://github.com/ghostserverd/docker-transmission-ghost/commit/f4e923b0cd034b1a90fb3b66a1aa37c06f861f4c

Thanks for bringing this up. Sorry for the confusion.
