### ISSUE TITLE
[Feature request] Filebot  with more detailed files

### ISSUE THREAD

**Issue by Mixie-12** [ghostserverd/mediaserver-docker#25]
Hi,
So from what I understand, radarr needs detailed info in the filename to identify the the proper quality.
My proposal is to use somthing like:
`{plex} - {tags} [{allOf{fn.matchAll(/UHD|4K|MVC|framepacked|FSBS|HSBS|HOU|FOU/)}{source}{vf}{aco}{channels}{vc}{hdr}{s3d}.join(' ')}]{' '+audioLanguages}{' '+subt}`

That creates filestructure somthing like this:
`/Movies/The Lost World - Jurassic Park (1997)/The Lost World - Jurassic Park (1997) [1080p, x264, AAC, 5.1].mp4`
Also maybe use move mode instead of copy mode so you dont have to manually delete the downloads/complete folder
Would love to contribute if wanted :)

**Comment by ghostserverd** [comment]
The filebot container supports custom formats via the `FILEBOT_FORMAT` environment variable. It defaults to `{plex}`, but you should be able to put any custom format in there if you want as well. I personally use `{plex} - {hd}` so I can keep `HD` and `UHD` versions of files without them overwriting each other.

https://github.com/ghostserverd/docker-filebot-ghost/blob/4.9.x/root/etc/services.d/filebot/run#L4

The container also supports custom actions via the `FILEBOT_ACTION` environment variable. The default action is `duplicate` because I want to keep the original file around for seeding purposes. Feel free to change that to `move` if you want. Although if your directories are set up right, `duplicate` will use hardlinks instead of actually copying the file which doesn't take up any additional space on your hard drive.

https://github.com/ghostserverd/docker-filebot-ghost/blob/4.9.x/root/etc/services.d/filebot/run#L6
