### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by gatsby0121** [ghostserverd/mediaserver-docker#26]
I updated your docker-compose file locally to include lidarr.  Can you point me in the direction for where I update the filebot script for renaming downloaded music?

**Comment by ghostserverd** [comment]
You're probably looking for the transmission and nzbget postprocessing scripts

https://github.com/ghostserverd/docker-transmission-ghost/blob/master/transmission-postprocess.sh

https://github.com/ghostserverd/docker-nzbget-ghost/blob/master/nzbget-postprocess.sh

although they already have lidarr support so it might just work for you.

I will say, filebot's support for music is pretty lackluster. I ended up moving away from it since it doesn't really match up with lidarr's database at all and you'll probably end up having to do a bunch of manual fixing of files anyway which defeats the purpose.

**Comment by gatsby0121** [comment]
Thanks, I've been having issues with it.  I see what you mean.
