### ISSUE TITLE
Prune downloaded media and mark it?

### ISSUE THREAD

**Issue by nicoarias81** [ghostserverd/mediaserver-docker#34]
Hi, love your work, thanks a lot!

After a download completes, filebots runs and copy's the file to the plex storage, this is ok.
After the copy, runs ok, the original file (in the completes dir) is not being deleted, so, i have 2 copys of the same media, wasting hd space.

Is this an expected behaviour?, i didnt find any configuration to manage this, but i might be missing something.

thanks!

**Comment by ghostserverd** [comment]
You can pass `FILEBOT_ACTION` as an environment variable. The default is `DUPLICATE`.

https://github.com/ghostserverd/mediaserver-docker/blob/master/docker-compose.yml#L96

https://www.filebot.net/forums/viewtopic.php?t=4915

```
DUPLICATE (i.e. hardlink if possible, or copy-on-write clone if possible, or copy if necessary)
```

Duplicate is the best option in my opinion. Ideally your directory structure should be set up to allow hardlinks which essentially creates an additional pointer to the file without duplicating it. So if you're set up for hardlinks, it won't actually waste any space.

You can change it to `move` if you want, but of course any other applications expecting it to be in the original location will no longer have access to it.

**Comment by nicoarias81** [comment]
just did a test, using hardlink it does not link, it does a copy.

I might be missing something on the file structure, i used the same that you showed on the env sample file.

**Comment by ghostserverd** [comment]
If you want to post your env file here and the output of ‘mount’ (after stopping the containers) so we can see what mounts could be interfering with hardlinks we might be able to figure it out.

**Comment by nicoarias81** [comment]
related part of the env file:

# ======== directories ========
CONFIG_DIR=/opt/dockervol/media_server/config
DOWNLOAD_DIR=/opt/media/media_server/downloads
MEDIA_DIR=/opt/media/media_server/media
TV_DIR=/opt/media/media_server/media/TV_Shows
MOVIES_DIR=/opt/media/media_server/media/Movies
### base dir should be a directory that contains both downloads and media to take advantage of hardlinks
BASE_DIR=/opt/media/media_server


# ======== filebot ========
FILEBOT_PORT=7676
### results in file names like "The Expanse - S02E07 - The Seventh Man - HD.mkv"
FILEBOT_FORMAT={plex} - {hd}
### prefer titles from the last 30 days but fall back to any title if there are none recent enough
FILEBOT_FILTER=any{ age < 30 }{ true } || !model.any{ it.age < 30 && it.age != null }
### duplicate will fall back to copy if hardlink fails. set to "hardlink" to confirm if hardlinks are working
FILEBOT_ACTION=hardlink
### filebot will intelligently decide whether or not to replace an existing copy
FILEBOT_CONFLICT=auto
### defaults to TheTVDB but TheTVDB has been having issues for most of 2020
FILEBOT_SERIES_DB=TheMovieDB::TV
FILEBOT_ANIME_DB=AniDB
FILEBOT_MOVIE_DB=TheMovieDB
FILEBOT_MUSIC_DB=ID3
### not currently functional
OPEN_SUB_USER=[REPLACEME]
### not currently functional
OPEN_SUB_PASS=[REPLACEME]

Mount points, its just a simple ubuntu server install, on a single disk, so its all on a single lvm:

sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,noexec,relatime,size=8121896k,nr_inodes=2030474,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1639968k,mode=755)
/dev/mapper/ubuntu--vg-ubuntu--lv on / type ext4 (rw,relatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=19278)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
/var/lib/snapd/snaps/core18_2128.snap on /snap/core18/2128 type squashfs (ro,nodev,relatime,x-gdu.hide)
/dev/nvme0n1p2 on /boot type ext4 (rw,relatime)
/dev/nvme0n1p1 on /boot/efi type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/var/lib/snapd/snaps/lxd_21029.snap on /snap/lxd/21029 type squashfs (ro,nodev,relatime,x-gdu.hide)
tmpfs on /run/snapd/ns type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1639968k,mode=755)
/var/lib/snapd/snaps/core18_2284.snap on /snap/core18/2284 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/core20_1328.snap on /snap/core20/1328 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/lxd_21835.snap on /snap/lxd/21835 type squashfs (ro,nodev,relatime,x-gdu.hide)
nsfs on /run/snapd/ns/lxd.mnt type nsfs (rw)
/var/lib/snapd/snaps/snapd_14978.snap on /snap/snapd/14978 type squashfs (ro,nodev,relatime,x-gdu.hide)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=1639964k,mode=700,uid=1000,gid=1000)

**Comment by ghostserverd** [comment]
That config looks fine. I tend to assume most people are mounting storage into their servers, and that's often a cause of hardlink issues since you can't hardlink across mounts. Filebot will be trying to hardlink from the `/share/downloads` directory into the `/share/media` directory inside the container.

1. Confirm that you're able to hardlink a file manually using `ln` from the download dir to the media dir (probably best to do it from within the filebot container so you can really be certain).
    ```
    docker exec -it filebot /bin/bash
    ln /share/downloads/complete/<somefile> /share/media/Movies/<somefile>
    ```

2. Try to force filebot to hardlink by setting the `FILEBOT_ACTION` to `hardlink` instead of `duplicate`. Then you'll want to look at the `amc.log` in your filebot config directory to see if there's a useful error returned.

3. Also an `amc.log` entry from an example where it's copying instead of hardlinking might have a clue as well.

**Comment by nicoarias81** [comment]
filebot is running with hardlink as action.

so, i did an inode check and its working.

With duplicate it was copying, so know i should be fine.

The only thing that i would like to confirm, is, since the file will dissapear from the downloads/complete list, sonarr will list it as missing and will try to download it again?

**Comment by ghostserverd** [comment]
So it's working with `hardlink`? That's weird that it works with `hardlink` as the action but doesn't hardlink with `duplicate` as the action. It's definitely supposed to. Might be worth asking on the filebot forums.

If your action is `hardlink`, it will create a second hardlink into the media directory, so the file will still be present in your downloads/complete directory. That being said, I have sonarr/radarr pointed at my media directory, not the downloads/complete directory. The downloads directory is only for actually downloading/seeding any given file. Sonarr and radarr shouldn't care about downloads since they're not doing any post-download management (filebot is). Sonarr and radarr should only care about the actual media directory (that plex is also looking at).

**Comment by nicoarias81** [comment]
I will do some testing with duplicate, just to be on the safe side.

Regarding sonarr/radarr missing file, since the file will be renamed when "moved" to the media dir, does sonnar keep tracks of the name change?

**Comment by ghostserverd** [comment]
sonarr / radarr should be configured to look at the media directory. When you add a TV show in sonarr for example, you will choose the directory that it should be in (e.g. `/tv/The Afterparty`). The suggested one should work just fine. You can change that directory, but for the most part you shouldn't need to. Filebot should move the completed episode into the same directory because it also uses the same databases that sonarr does for renaming. So once it gets moved, sonarr will now see it renamed properly without any release group information or anything, and it will recognize that it's now available in the media library.

**Comment by nicoarias81** [comment]
cool, thanks for the explanation. I will keep and eye.

again, thanks for your awesome work!
