### ISSUE TITLE
PIA VPN Container for Transmission

### ISSUE THREAD

**Issue by iamon13** [ghostserverd/mediaserver-docker#6]
Hi there! 

I am interested in adding a VPN to my docker-compose file specifically for the Transmission container, and I'm running into some issues setting everything up. For context I am using a PIA (Private Internet Access) VPN, and I've tried a couple of approaches, including adding an OpenVPN container to my compose file and setting the network settings for Transmission to use the VPN (a la [this project](https://github.com/dperson/openvpn-client)), as well as replacing the Transmission container with a different one that combines Transmission and PIA in one container (a la [this project](https://github.com/haugene/docker-transmission-openvpn)). For the latter project, I am able to successfully download files using Transmission, but the files ignore the directories I have set up in the docker-compose, and instead download to a directory in my config folder for the container.

I am trying to avoid running a VPN on my machine itself, as I understand there are some issues with accessing Plex remotely when a VPN is running on the same machine. Consequently, my end-goal is to have **only** Transmission's incoming/outgoing traffic go through the VPN container.

Any ideas and/or suggestions?

**Comment by ghostserverd** [comment]
Hey there. I don't have any experience setting up openvpn, but I did just update the compose file and readme with an example of using a wireguard container to proxy all traffic for `nzbget` through a VPN. 

I have been testing it with mullvad and it works great. PIA does not yet have generally available support for wireguard, but they're actively working on it.

You may also be able to set up a standalone openvpn container and follow the same pattern I used to connect a different service (like `transmission`) to its network.

If you do go this route, you'll definitely need to set up a reverse proxy since once you set the network mode of a container to use another container's network, it's no longer accessible outside of `localhost` and the docker bridge overlay network.

Hope that helps!

**Comment by ghostserverd** [comment]
I'm going to resolve this but feel free to re-open.
