### ISSUE TITLE
NZBGet Download Issues

### ISSUE THREAD

**Issue by iamon13** [ghostserverd/mediaserver-docker#8]
Hi ghostserverd.

I am having trouble finding where successful downloads from NZBGet are moved. I have everything set to the defaults in the Paths section of the NZBGet container, and when the download is initially started the .nzb file is successfully downloaded in the nzb directory of the downloads directory stated in my .env file. However, when the download is completed and the .nzb is moved from Downloads to History in NZBGet and unpacked, I can't find the downloaded file, and furthermore when looking in FileBot's amc file I see nothing regarding FileBot picking up, renaming, and moving the file to my TV Shows directory. I have the directory in Sonarr configured correctly, and when I use torrents with Transmission the process works flawlessly. 

In the History tab for the .nzb, it says the Destination directory is: 
`/downloads/complete/Series/episode_details_etc`

In NZBGet Paths, paths are set as:

- MainDir: /downloads

- DestDir: ${MainDir}/complete

- InterDir: empty

- NzbDir: ${MainDir}/nzb

Any thoughts?

**Comment by gatsby0121** [comment]
I'm having the same issue with Sonarr.  

BTW, how did you configure your dnsmasq.conf or dnsmasq.d files?

**Comment by ghostserverd** [comment]
@iamon13 post your .env and I’ll take a look.

@gatsby0121 what do you mean you have the same issue with Sonarr? Sonarr shouldn’t be triggering filebot, and you should have drone factory and completed download handling disabled in both sonarr and radarr.

**Comment by gatsby0121** [comment]
I think my problem is from the dnsmasq part.  I think it's just not seeing the file when it's done.

netdata         | 2020-06-04 15:26:31: cgroup-name.sh: WARNING: cannot find the name of docker container '3893f7e2546c568112cd8d90cc7823fea957f9d236a970ef6c786adfdf0d6b23'

I'm not sure how to implement your dnsmasq.conf recommendation.

Can you give an example entry for dnsmasq.d in reference to this comment?  And is this applied in the host?

3. If SERVICE_NAMES is set (a list of services to make available from within the wireguard network), write each service name individually to /etc/dnsmasq.conf to force 127.0.0.11 as the DNS server for each service address. This is nice because you don't have to write an alias for each service to make available, but you do need to list out all of the services. A sample SERVICE_NAMES variable is set in the docker-compose.yml file. It shouldn't need to be modified, but if there is a reason to, open an issue and I can make it pull from the .env file.

**Comment by iamon13** [comment]
@ghostserverd I appreciate the quick turn-around time. Attached are my .env and docker-compose.yml files. 

Thanks!
[docker_info.zip](https://github.com/ghostserverd/mediaserver-docker/files/4731846/docker_info.zip)

**Comment by ghostserverd** [comment]
@gatsby0121 can you open a different issue? iamon13 isn't using the wireguard container at all, so these two things are unrelated.

**Comment by ghostserverd** [comment]
@iamon13 fwiw my `MainDir` is set to `/downloads/nzb`, but I don't really think that's the issue.

If you go to the messages tab in `nzbget` and filter by `nzbget-postprocess`, do you see any messages?

Each post-process execution should start with `Executing post-process-script nzbget-postprocess.sh for <name>` and end with `Post-process-script nzbget-postprocess.sh for <name>`

**Comment by iamon13** [comment]
@ghostserverd I tried another download and changed my MainDir to /downloads/nzb as you have, and funny enough that did help create the completed and all other directories needed, so at least I can see where the file was actually downloaded to.

I am still having the issue of FileBot not picking up the file and processing it correctly. amc script is unchanged, and when I went into the messages tab in `nzbget` and filter by `nzbget-postprocess` no messages showed up. Fwiw the `Extension Scripts` section of `nzbget` has no entries as you can see in the screenshot below. Not sure if that's how the post processing is supposed to take place, but I figured I'd mention that. 

![image](https://user-images.githubusercontent.com/34734889/83806333-35efbb80-a666-11ea-8e3f-73681cc6a52b.png)

**Comment by ghostserverd** [comment]
Yeah the fact that you're not seeing any logs prefixed with `nzbget-postprocess` indicates that it's not even trying to trigger the post process script (which is what calls out to filebot).

If you click on that `Choose` button next to the `Extensions` field, do you see an option to choose `nzbget-postprocess`? If so, select it. If not, could you try just manually adding `nzbget-postprocess.sh` in the Extensions field and give that a shot?

You’ll also probably need to go back to PATHS and make the ScriptDir be `/usr/local/bin`

**Comment by iamon13** [comment]
I couldn't select the `nzbget-postprocess`, as it didn't seem to exist. I went to the FileBot [GitHub](https://github.com/filebot/plugins/blob/master/bash/nzbget-postprocess.sh) and forked the `nzbget-postprocess.sh` file from there, added it to the ScriptDir (which I changed to /usr/local/bin at your recommendation), and now FileBot is successfully picking up the file and completing the process! This is working for TV Shows, haven't had a chance to try with Movies yet, though I expect it will work the same. Thanks again for your help as always! You can consider the issue closed from my end.

**Comment by ghostserverd** [comment]
That’s a tad scary since the container itself copies the script to `/usr/local/bin` so it definitely should be in there. But my guess is it will still work even after a container rebuild now that you have the scripts dir pointed there.

Sorry for the confusion and thanks for opening an issue! I’ll get the nzbget container built to actually integrate with filebot automatically.

**Comment by ghostserverd** [comment]
I updated the nzbget container to override the necessary settings so it will be able to call filebot by default without requiring manual configuration. The compose file, readme, and sample env file have all been updated as well.
